# SPDX-FileCopyrightText: 2026 Tanner Golden
# SPDX-License-Identifier: MIT
"""A folder log is generated from the folder, or it is a list that drifts.

The template repositories give every folder a README that logs each file in
it. Kept by hand, those logs went stale the first time somebody added a file
without remembering the row, and nothing noticed: a log that omits a file
reads exactly like a complete one.

`update-doc-indexes.py` already ends that for the docs tree. Its `log` style
extends it to any folder: one row per entry, each described by what the
entry says about itself, regenerated by `--tree` wherever a block sits in
the repository, and checked whitespace-insensitively like every other block.

These tests pin what a reader relies on: every file is there, nothing the
repository ignores is, each description comes from its file, a description
nothing can supply survives regeneration, and a run that found no block at
all does not report a pass.
"""

from __future__ import annotations

import subprocess

import pytest
from conftest import ROOT, load_script, load_yaml

SCRIPT = ROOT / "scripts/update-doc-indexes.py"
indexes = load_script("scripts/update-doc-indexes.py")

LOG = "<!-- AUTO-INDEX:BEGIN dir=. style=log -->\n<!-- AUTO-INDEX:END -->\n"


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def block(text: str) -> str:
    return text.split("AUTO-INDEX:BEGIN", 1)[1].split("AUTO-INDEX:END", 1)[0]


class TestEveryEntryIsLogged:
    def test_folders_come_first_then_files_each_linked(self, tmp_path, monkeypatch):
        write(tmp_path / "pkg/README.md", "<!--\ndescription: 'The package.'\n-->\n")
        write(tmp_path / "loose/notes.txt", "x\n")
        write(tmp_path / "beta.py", '"""Beta does things."""\n')
        write(tmp_path / "Alpha.md", "<!--\ndescription: 'Alpha.'\n-->\n")
        readme = write(tmp_path / "README.md", "# Here\n\n" + LOG)
        monkeypatch.chdir(tmp_path)

        assert indexes.process("README.md", write=True) is True
        rows = [ln for ln in block(readme.read_text(encoding="utf-8")).splitlines() if ln.startswith("| [")]
        assert [r.split("`")[1] for r in rows] == ["loose/", "pkg/", "Alpha.md", "beta.py", "README.md"]
        assert "[`pkg/`](pkg/README.md)" in rows[1], "a folder with a README links to it"
        assert "[`loose/`](loose/)" in rows[0], "a folder without one links to the folder"

    def test_the_hosting_file_is_listed_as_itself(self, tmp_path, monkeypatch):
        readme = write(tmp_path / "README.md", LOG)
        monkeypatch.chdir(tmp_path)
        indexes.process("README.md", write=True)
        assert "This file." in readme.read_text(encoding="utf-8")

    def test_an_ignored_file_is_left_out(self, git_repo, monkeypatch):
        write(git_repo / ".gitignore", "*.log\n")
        write(git_repo / "debug.log", "noise\n")
        readme = write(git_repo / "README.md", LOG)
        monkeypatch.chdir(git_repo)
        indexes.process("README.md", write=True)
        text = block(readme.read_text(encoding="utf-8"))
        assert "debug.log" not in text, "a file git ignores reached its folder's log"
        assert "`.gitignore`" in text

    def test_an_excluded_pattern_is_left_out(self, tmp_path, monkeypatch):
        write(tmp_path / "badge.svg", "<svg/>\n")
        readme = write(
            tmp_path / "README.md",
            "<!-- AUTO-INDEX:BEGIN dir=. style=log exclude=*.svg -->\n<!-- AUTO-INDEX:END -->\n",
        )
        monkeypatch.chdir(tmp_path)
        indexes.process("README.md", write=True)
        assert "badge.svg" not in readme.read_text(encoding="utf-8")

    def test_a_folder_holding_nothing_reads_none_yet(self, tmp_path, monkeypatch):
        (tmp_path / "empty").mkdir()
        readme = write(
            tmp_path / "README.md",
            "<!-- AUTO-INDEX:BEGIN dir=./empty style=log -->\n<!-- AUTO-INDEX:END -->\n",
        )
        monkeypatch.chdir(tmp_path)
        indexes.process("README.md", write=True)
        assert "_none yet_" in readme.read_text(encoding="utf-8")

    def test_a_missing_folder_is_an_error_not_an_empty_log(self, tmp_path, monkeypatch):
        write(tmp_path / "README.md", "<!-- AUTO-INDEX:BEGIN dir=./gone style=log -->\n<!-- AUTO-INDEX:END -->\n")
        monkeypatch.chdir(tmp_path)
        with pytest.raises(SystemExit):
            indexes.process("README.md", write=False)


class TestDirectoriesResolveFromTheHost:
    def test_a_dot_relative_dir_is_the_hosts_folder(self, tmp_path, monkeypatch):
        write(tmp_path / "deep/inner/x.txt", "x\n")
        readme = write(tmp_path / "deep/README.md", LOG)
        monkeypatch.chdir(tmp_path)
        indexes.process("deep/README.md", write=True)
        assert "[`inner/`](inner/)" in readme.read_text(encoding="utf-8")

    def test_a_parent_relative_dir_reaches_a_sibling(self, tmp_path, monkeypatch):
        write(tmp_path / "other/y.txt", "y\n")
        readme = write(
            tmp_path / "here/README.md",
            "<!-- AUTO-INDEX:BEGIN dir=../other style=log -->\n<!-- AUTO-INDEX:END -->\n",
        )
        monkeypatch.chdir(tmp_path)
        indexes.process("here/README.md", write=True)
        assert "[`y.txt`](../other/y.txt)" in readme.read_text(encoding="utf-8")

    def test_a_bare_dir_is_still_under_docs(self):
        assert indexes.resolve_dir("distribution", "docs/Hub.md") == "docs/distribution"


class TestEachEntryDescribesItself:
    def test_markdown_uses_its_frontmatter_in_either_form(self, tmp_path):
        comment = write(tmp_path / "A.md", "<!--\ndescription: 'It''s the comment form.'\n-->\n")
        fence = write(tmp_path / "B.md", "---\ndescription: The fence form.\n---\n")
        assert indexes.describe(str(comment)) == "It's the comment form."
        assert indexes.describe(str(fence)) == "The fence form."

    def test_markdown_without_frontmatter_uses_its_opening_comment(self, tmp_path):
        path = write(tmp_path / "pull_request_template.md", "<!--\nThis becomes the body. More after.\n-->\n")
        assert indexes.describe(str(path)) == "This becomes the body. More after."

    def test_python_uses_its_docstring_summary(self, tmp_path):
        path = write(tmp_path / "tool.py", '"""Validate the configuration nothing else parses.\n\nLong.\n"""\n')
        assert indexes.describe(str(path)) == "Validate the configuration nothing else parses."

    def test_a_form_uses_its_description_key(self, tmp_path):
        path = write(tmp_path / "Bug.yaml", "name: 'Bug'\ndescription: 'Report a defect.'\nbody: []\n")
        assert indexes.describe(str(path)) == "Report a defect."

    def test_a_discussion_form_uses_the_prose_under_its_heading(self, tmp_path):
        path = write(
            tmp_path / "q-a.yaml",
            "# Keep the prefill short.\n"
            "title: 'Q&A'\n"
            "body:\n"
            "  - type: markdown\n"
            "    attributes:\n"
            "      value: |\n"
            "        ## Questions\n"
            "        Ask how-do-I questions and get help from the community. Mark the answer.\n"
            "  - type: textarea\n",
        )
        assert indexes.describe(str(path)) == "Ask how-do-I questions and get help from the community."

    def test_a_stub_skips_its_installed_from_banner(self, tmp_path):
        path = write(
            tmp_path / "checks.yml",
            "# Installed from tannergolden/standards. Edit freely: this file is YOURS.\n"
            "#\n"
            "# Everything that verifies a change, in one file.\n"
            "name: 'Checks'\n",
        )
        assert indexes.describe(str(path)) == "Everything that verifies a change, in one file."

    def test_a_purpose_paragraph_wins_over_a_title_line(self, tmp_path):
        path = write(
            tmp_path / "parity.yml",
            "# --- This Repository's Own Contract ---\n#\n# 📐 Template Parity\n#\n"
            "# Purpose: enforce the contract, so drift fails a check.\n",
        )
        assert indexes.describe(str(path)) == "Enforce the contract, so drift fails a check."

    def test_separators_urls_and_the_files_own_name_are_skipped(self, tmp_path):
        path = write(
            tmp_path / "dependabot.yml",
            "# =====\n# .github/dependabot.yml\n# Dependabot - automated updates\n# https://example.invalid/docs\n# =====\n",
        )
        assert indexes.describe(str(path)) == "Dependabot - automated updates"

    def test_jsonc_reads_the_comment_inside_its_braces(self, tmp_path):
        path = write(tmp_path / "extensions.json", '{\n  // Recommended for everyone.\n  "x": []\n}\n')
        assert indexes.describe(str(path)) == "Recommended for everyone."

    def test_json_without_comments_reads_a_slash_slash_key(self, tmp_path):
        path = write(tmp_path / ".markdownlint.json", '{\n  "//": "Repository-wide rules. More.",\n  "MD013": false\n}\n')
        assert indexes.describe(str(path)) == "Repository-wide rules. More."

    def test_a_json_lock_reads_its_slash_slash_key(self, tmp_path):
        path = write(tmp_path / "template-sync.lock", '{\n  "//": "Where each file was synced from.",\n  "format": 1\n}\n')
        assert indexes.describe(str(path)) == "Where each file was synced from."

    def test_a_lock_that_is_not_json_says_nothing(self, tmp_path):
        path = write(tmp_path / "poetry.lock", "[[package]]\nname = 'x'\n")
        assert indexes.describe(str(path)) == ""

    def test_a_plain_text_file_named_in_capitals_uses_its_first_line(self, tmp_path):
        path = write(tmp_path / "LICENSE", "MIT License\n\nCopyright (c) 2026\n")
        assert indexes.describe(str(path)) == "MIT License"

    def test_a_short_first_sentence_takes_the_next(self, tmp_path):
        path = write(tmp_path / "a.sh", "#!/usr/bin/env bash\n# Dispatch-only. Run it to apply the labels.\n")
        assert indexes.describe(str(path)) == "Dispatch-only. Run it to apply the labels."

    def test_a_trailing_colon_fragment_is_not_appended(self, tmp_path):
        path = write(tmp_path / "b.yml", "# Keeps the tab readable. Everything goes except:\n")
        assert indexes.describe(str(path)) == "Keeps the tab readable."

    @pytest.mark.parametrize(
        "name, content",
        [
            (".editorconfig", "root = true\n"),
            ("logo.png", "\x89PNG\x00\x00"),
            ("notes.txt", "just some words\n"),
        ],
    )
    def test_a_file_with_nothing_to_say_says_nothing(self, tmp_path, name, content):
        path = write(tmp_path / name, content)
        assert indexes.describe(str(path)) == ""

    def test_a_folder_is_described_by_its_readme(self, tmp_path):
        write(tmp_path / "src/README.md", "<!--\ndescription: 'The source.'\n-->\n")
        assert indexes.describe(str(tmp_path / "src")) == "The source."


class TestADescriptionNothingCanSupplySurvives:
    def test_a_hand_written_row_is_kept(self, tmp_path, monkeypatch):
        write(tmp_path / "logo.png", "\x89PNG\x00")
        readme = write(tmp_path / "README.md", LOG)
        monkeypatch.chdir(tmp_path)
        indexes.process("README.md", write=True)
        text = readme.read_text(encoding="utf-8")
        assert "| -" in text.split("logo.png", 1)[1].split("\n", 1)[0], "no description yet reads '-'"

        text = text.replace(text.split("logo.png", 1)[1].split("\n", 1)[0], "`](logo.png) | The project mark |")
        readme.write_text(text, encoding="utf-8")
        assert indexes.process("README.md", write=False) is False, "a kept description was called stale"
        assert indexes.process("README.md", write=True) is False
        assert "The project mark" in readme.read_text(encoding="utf-8")

    def test_a_file_that_describes_itself_overrides_its_row(self, tmp_path, monkeypatch):
        write(tmp_path / "tool.py", '"""The real purpose."""\n')
        readme = write(
            tmp_path / "README.md",
            "<!-- AUTO-INDEX:BEGIN dir=. style=log -->\n"
            "| Entry | Purpose |\n| :-- | :-- |\n| [`tool.py`](tool.py) | A stale claim |\n"
            "<!-- AUTO-INDEX:END -->\n",
        )
        monkeypatch.chdir(tmp_path)
        assert indexes.process("README.md", write=True) is True
        text = readme.read_text(encoding="utf-8")
        assert "The real purpose." in text and "A stale claim" not in text


class TestFieldsAddColumns:
    def test_name_and_triggers(self, tmp_path, monkeypatch):
        write(
            tmp_path / "checks.yml",
            "# Verifies a change, every time it is pushed.\n"
            "name: 'Checks'\n"
            "on:\n"
            "  push:\n"
            "    branches: ['Preview']\n"
            "  schedule:\n"
            "    - cron: '0 3 * * 1'\n"
            "  workflow_dispatch:\n"
            "jobs: {}\n",
        )
        readme = write(
            tmp_path / "README.md",
            "<!-- AUTO-INDEX:BEGIN dir=. style=log fields=name,on -->\n<!-- AUTO-INDEX:END -->\n",
        )
        monkeypatch.chdir(tmp_path)
        indexes.process("README.md", write=True)
        text = readme.read_text(encoding="utf-8")
        assert "| Entry" in text and "| Name" in text and "| Triggers" in text and "| Purpose" in text
        row = next(ln for ln in text.splitlines() if "checks.yml" in ln)
        assert "Checks" in row
        assert "`push` (`Preview`), `schedule` (`0 3 * * 1`), `workflow_dispatch`" in row

    @pytest.mark.parametrize(
        "on, expected",
        [("on: push\n", "`push`"), ("on: [push, pull_request]\n", "`push`, `pull_request`")],
    )
    def test_inline_triggers(self, on, expected):
        assert indexes.workflow_triggers(f"name: x\n{on}jobs: {{}}\n") == expected

    def test_any_other_field_is_read_from_frontmatter(self, tmp_path, monkeypatch):
        # How a folder of decision records doubles as their index: the log
        # carries each record's status, date and evidence beside its purpose.
        write(
            tmp_path / "ADR-0001-Use-Postgres.md",
            "<!--\ntitle: 'ADR'\ndescription: 'Use Postgres for every service.'\n"
            "status: 'Accepted'\ndate: '2026-01-02'\nevidence: '[Report](https://example.com/r.md)'\n-->\n",
        )
        write(tmp_path / "flow.svg", "<svg/>\n")
        readme = write(
            tmp_path / "README.md",
            "<!-- AUTO-INDEX:BEGIN dir=. style=log fields=status,date,evidence -->\n<!-- AUTO-INDEX:END -->\n",
        )
        monkeypatch.chdir(tmp_path)
        indexes.process("README.md", write=True)
        lines = block(readme.read_text(encoding="utf-8")).splitlines()
        header = next(ln for ln in lines if ln.startswith("| Entry"))
        assert [c.strip() for c in header.strip("|").split("|")] == ["Entry", "Status", "Date", "Evidence", "Purpose"]
        record = next(ln for ln in lines if "ADR-0001" in ln)
        assert [c.strip() for c in record.strip("|").split("|")][1:] == [
            "Accepted",
            "2026-01-02",
            "[Report](https://example.com/r.md)",
            "Use Postgres for every service.",
        ]
        image = next(ln for ln in lines if "flow.svg" in ln)
        assert [c.strip() for c in image.strip("|").split("|")][1:4] == ["-", "-", "-"], "no frontmatter, no value"

    def test_a_field_that_cannot_be_a_key_is_refused(self, tmp_path, monkeypatch):
        write(
            tmp_path / "README.md",
            "<!-- AUTO-INDEX:BEGIN dir=. style=log fields=a/b -->\n<!-- AUTO-INDEX:END -->\n",
        )
        monkeypatch.chdir(tmp_path)
        with pytest.raises(SystemExit):
            indexes.process("README.md", write=False)


class TestCellsAreSafe:
    def test_a_pipe_cannot_split_a_row(self):
        assert indexes.cell("a | b") == r"a \| b"

    def test_non_ascii_becomes_entities_so_widths_match_the_formatter(self):
        assert indexes.cell("🚦 Checks") == "&#x1F6A6; Checks"

    def test_angle_brackets_cannot_open_a_tag(self):
        assert indexes.cell("<Area>") == "&lt;Area&gt;"


class TestRecordsReadTheCommentForm:
    def test_a_record_with_hidden_frontmatter_has_its_fields_read(self, tmp_path, monkeypatch):
        write(
            tmp_path / "ADR-0001-Use-Postgres.md",
            "<!--\ntitle: 'ADR'\nstatus: 'Accepted'\ndate: '2026-01-02'\n-->\n# ADR\n",
        )
        register = write(
            tmp_path / "Register.md",
            "<!-- AUTO-INDEX:BEGIN dir=. style=records fields=status,date "
            "headers=Decision,Status,Date sort=date:desc -->\n<!-- AUTO-INDEX:END -->\n",
        )
        monkeypatch.chdir(tmp_path)
        indexes.process("Register.md", write=True)
        row = next(ln for ln in register.read_text(encoding="utf-8").splitlines() if "ADR 0001" in ln)
        assert "Accepted" in row and "2026-01-02" in row


class TestTheWholeTreeMode:
    def run(self, cwd, *args):
        return subprocess.run(
            ["python3", str(SCRIPT), *args], cwd=str(cwd), capture_output=True, text=True
        )

    def test_it_works_without_a_docs_folder(self, tmp_path):
        write(tmp_path / "src/app.py", '"""The app."""\n')
        write(tmp_path / "src/README.md", LOG)
        assert self.run(tmp_path, "--tree", "--check").returncode == 1, "a fresh block is stale"
        assert self.run(tmp_path, "--tree", "--write").returncode == 0
        result = self.run(tmp_path, "--tree", "--check")
        assert result.returncode == 0, result.stdout + result.stderr
        assert "The app." in (tmp_path / "src/README.md").read_text(encoding="utf-8")

    def test_a_new_file_makes_its_folder_log_stale(self, tmp_path):
        write(tmp_path / "README.md", LOG)
        assert self.run(tmp_path, "--tree", "--write").returncode == 0
        write(tmp_path / "later.py", '"""Added after."""\n')
        result = self.run(tmp_path, "--tree", "--check")
        assert result.returncode == 1
        assert "README.md" in result.stdout, "the stale file is not named"

    def test_a_tree_with_no_block_does_not_pass(self, tmp_path):
        write(tmp_path / "README.md", "# Nothing generated here\n")
        result = self.run(tmp_path, "--tree", "--check")
        assert result.returncode == 1
        assert "no auto-index block" in result.stdout.lower()


class TestTheWorkflowChainHoldsTogether:
    """Three files in two places, any of which can drift from the others."""

    def test_the_action_runs_the_generator_over_the_whole_tree(self):
        action = (ROOT / "actions/update-indexes/action.yml").read_text(encoding="utf-8")
        assert "scripts/update-doc-indexes.py" in action
        assert "--tree" in action, "the action would only ever see docs/"

    def test_the_count_the_action_reads_is_the_one_the_script_prints(self, tmp_path):
        """The action counts rewritten files by the lines the script prefixes
        with 📝, so a reworded message would report every run as a no-op."""
        action = (ROOT / "actions/update-indexes/action.yml").read_text(encoding="utf-8")
        assert "'^📝 '" in action
        write(tmp_path / "README.md", LOG)
        result = subprocess.run(
            ["python3", str(SCRIPT), "--tree", "--write"], cwd=str(tmp_path), capture_output=True, text=True
        )
        assert "📝 README.md" in result.stdout.splitlines()

    def test_the_workflow_regenerates_then_proposes_a_pull_request(self):
        doc = load_yaml(".github/workflows/auto-index.yml")
        job = doc["jobs"]["index"]
        uses = [step.get("uses", "") for step in job["steps"]]
        assert any("/actions/update-indexes@" in u for u in uses)
        assert any("/actions/open-pr@" in u for u in uses), "indexes would be regenerated and dropped"
        assert job["permissions"] == {"contents": "write", "pull-requests": "write"}

    def test_the_documented_stub_asks_for_what_the_job_needs(self):
        header = (ROOT / ".github/workflows/auto-index.yml").read_text(encoding="utf-8").split("\n# ---\n", 1)[0]
        assert "contents: write" in header and "pull-requests: write" in header
