#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Tanner Golden
# SPDX-License-Identifier: MIT
"""Regenerate the label reference tables from the taxonomy.

`data/labels.yml` is the registry; `docs/references/Repository-Labels.md`
describes it. Kept by hand, the two drift silently - the colour of a label
is exactly the kind of detail nobody re-reads, and the documentation had
already fallen behind on several before this script existed.

So the per-family tables are generated between markers, and CI runs this
with --check. The prose around them stays hand-written: what a family is
*for* is a decision, not a fact about the file.

    python3 scripts/update-label-docs.py            # rewrite in place
    python3 scripts/update-label-docs.py --check    # fail if stale

Stdlib only, like every other script here, so it runs on a bare runner.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LABELS = ROOT / "data" / "labels.yml"
DOC = ROOT / "docs" / "references" / "Repository-Labels.md"

BEGIN = "<!-- BEGIN GENERATED LABELS -->"
END = "<!-- END GENERATED LABELS -->"

# Families are emitted in this order, with the heading each one gets. A
# family present in the registry but missing here is still emitted, under its
# bare prefix, so adding one cannot silently drop it from the documentation.
FAMILIES = [
    ("priority", "🚦 Priority"),
    ("semver", "📦 Semantic Versioning"),
    ("risk", "☢️ Risk"),
    ("status", "📋 Status & Lifecycle"),
    ("ci", "🚨 Continuous Integration"),
    ("size", "👚 Size"),
    ("type", "🏷️ Change Types"),
    ("area", "🏗️ Technical Areas"),
    ("", "🤝 GitHub Defaults & Community"),
]

FIELD = re.compile(r"^(?:-\s+)?(name|color|description|renamed_from):\s*'(.*)'\s*$")


def load(path: pathlib.Path) -> list[dict[str, str]]:
    """Parse the registry without PyYAML, which a bare runner may not have."""
    labels: list[dict[str, str]] = []
    current: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = FIELD.match(line)
        if not m:
            sys.exit(f"unparseable line in {path}: {raw!r}")
        key, value = m.group(1), m.group(2).replace("''", "'")
        if key == "name":
            current = {"name": value}
            labels.append(current)
        else:
            current[key] = value

    # ⚠️ VALIDATED HERE, WHERE THE ENTRY STILL HAS A NAME. `render()` reads
    # `label["description"]` and `label["color"]` by subscript, and the
    # GitHub labels API permits a label with neither, so a hand-edited
    # registry that omits one used to die with a bare KeyError naming the
    # missing KEY and not the offending LABEL. A traceback in an Actions log
    # says which line of somebody else's code blew up; it does not say what
    # to change.
    for entry in labels:
        missing = sorted({"color", "description"} - entry.keys())
        if missing:
            sys.exit(
                f"::error::{path}: the label '{entry['name']}' has no "
                f"{' and no '.join(missing)}. Every entry needs a name, a colour and a "
                "description; add the missing field to the registry."
            )
    return labels


def family_of(name: str) -> str:
    return name.split(":")[0] if ":" in name else ""


def render(labels: list[dict[str, str]]) -> str:
    grouped: dict[str, list[dict[str, str]]] = {}
    for label in labels:
        grouped.setdefault(family_of(label["name"]), []).append(label)

    known = [f for f, _ in FAMILIES]
    ordered = FAMILIES + [(f, f) for f in grouped if f not in known]

    out: list[str] = [
        BEGIN,
        "",
        "<!-- Generated by scripts/update-label-docs.py from data/labels.yml.",
        "     Edit the registry, then run the script. Hand edits here are",
        "     overwritten and CI fails on drift. -->",
        "",
    ]
    for key, heading in ordered:
        items = grouped.get(key)
        if not items:
            continue
        out += [
            f"### {heading}",
            "",
            "| Label | Colour | Meaning |",
            "| :---- | :----- | :------ |",
        ]
        for label in items:
            desc = label["description"].replace("|", "\\|")
            out.append(f"| `{label['name']}` | `#{label['color']}` | {desc} |")
        out.append("")

    out += [
        f"_{len(labels)} labels._ The registry is "
        "[`data/labels.yml`](../../data/labels.yml).",
        "",
        END,
    ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the document is out of date")
    args = ap.parse_args()

    if not LABELS.exists():
        sys.exit(f"{LABELS} does not exist")
    if not DOC.exists():
        sys.exit(f"{DOC} does not exist")

    text = DOC.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit(f"{DOC} has no {BEGIN} / {END} markers to write between")

    generated = render(load(LABELS))
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    updated = pattern.sub(lambda _: generated, text)

    if updated == text:
        print(f"{DOC.relative_to(ROOT)} is up to date")
        return 0
    if args.check:
        print(f"::error title=Label documentation::{DOC.relative_to(ROOT)} is out of date; "
              f"run python3 scripts/update-label-docs.py")
        return 1
    DOC.write_text(updated, encoding="utf-8")
    print(f"{DOC.relative_to(ROOT)} updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
